### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-go-instrumentation

### ISSUE THREAD

**Issue by edeNFed** [open-telemetry/community#1377]
### Affected Repository

[opentelemetry-go-instrumentation](https://github.com/open-telemetry/opentelemetry-go-instrumentation)

### Requested changes

Add `DOCKER_USERNAME` and `DOCKER_PASSWORD` username/password for Docker Hub as secrets to this repository.

### Purpose

We will be publishing container images to the OpenTelemetry Docker Hub account, see: https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/31
 
### Expected Duration

Forever

### Repository Maintainers

@open-telemetry/go-instrumentaiton-maintainers

**Comment by arminru** [comment]
@tigrannajaryan I think you have access to our Docker account. Could you look into that, please?

Would it also be possible to add an [access token](https://docs.docker.com/docker-hub/access-tokens/) instead of the username and password?

**Comment by tigrannajaryan** [comment]
Done. DOCKER_PASSWORD and DOCKER_USERNAME secrets added to https://github.com/open-telemetry/opentelemetry-go-instrumentation.

@arminru yes, I always add access tokens, separate for each repo.

**Comment by TylerHelmuth** [comment]
@tigrannajaryan can you check on the secrets added to https://github.com/open-telemetry/opentelemetry-go-instrumentation?  We just tried to push our first image but got [scope permission issues](https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/4724518902/jobs/8381827448).

**Comment by TylerHelmuth** [comment]
I'm no dockerhub expert, but [these docs](https://docs.docker.com/docker-hub/repos/create/) seem to imply the repository needs to be manually create first.

**Comment by tigrannajaryan** [comment]
I created https://hub.docker.com/r/otel/autoinstrumentation-go manually.

**Comment by TylerHelmuth** [comment]
@tigrannajaryan we are still experiencing the `scope_permission` issue and I was able to reproduce it in my own repository by generating a Read-Only token setting it in `DOCKER_PASSWORD`: https://github.com/TylerHelmuth/opentelemetry-go-instrumentation/actions/runs/4736205676/jobs/8407432789.  Can you take another look at the token being used for the opentelemetry-go-instrumentation repository and confirm it has write access?

**Comment by tigrannajaryan** [comment]
I created a new access token for Read & Write access:

![image](https://user-images.githubusercontent.com/4194920/232902502-817c89ae-0e1e-4f44-b4c3-5fdde13addbe.png)

Try again now.

**Comment by TylerHelmuth** [comment]
@tigrannajaryan are you allowed to share the username we're using?

**Comment by tigrannajaryan** [comment]
Yes, the username for docker hub is `otelbot`. All repos use this username. Passwords are different for each repo.
